/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NaiveToolProviders: typeof import('./components/naive-tool-providers/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NResult: typeof import('naive-ui')['NResult']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/svg-icon/index.vue')['default']
  }
}

// For TSX support
declare global {
    const NaiveToolProviders: (typeof import('./components/naive-tool-providers/index.vue'))['default']
    const NButton: (typeof import('naive-ui'))['NButton']
    const NConfigProvider: (typeof import('naive-ui'))['NConfigProvider']
    const NResult: (typeof import('naive-ui'))['NResult']
    const RouterLink: (typeof import('vue-router'))['RouterLink']
    const RouterView: (typeof import('vue-router'))['RouterView']
    const SvgIcon: (typeof import('./components/svg-icon/index.vue'))['default']
}
