/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/svg-icon/index.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarResult: typeof import('@varlet/ui')['_ResultComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}

// For TSX support
declare global {
    const RouterLink: (typeof import('vue-router'))['RouterLink']
    const RouterView: (typeof import('vue-router'))['RouterView']
    const SvgIcon: (typeof import('./components/svg-icon/index.vue'))['default']
    const VarButton: (typeof import('@varlet/ui'))['_ButtonComponent']
    const VarResult: (typeof import('@varlet/ui'))['_ResultComponent']
    const VarSpace: (typeof import('@varlet/ui'))['_SpaceComponent']
}
